### ISSUE TITLE
[Feature] Online statuses

### ISSUE THREAD

**Issue by colingoodman** [tiberloop/squidchat-issues#10]
**Is your feature request related to a problem? Please describe.**
The back end should have support for online/offline statuses ready to go. It just needs front end implementation.

**Describe the solution you'd like**
If a user is online / open socket, an indicator (such as a green circle) next to their name is present when appropriate, such as in the list of DMs. To be clear, the status indicator should not _necessarily_ be present within chats, however (as we discussed) there could be fun ways to present this information (like snapchat does or whatever)

**Comment by heisler98** [comment]
How do I determine which users are online at the time of app initialization?

**Comment by heisler98** [comment]
Lol nevermind found it

**Comment by heisler98** [comment]
The `/ws/online` endpoint says some users are online that likely aren't online. I know I have no sockets open, but it says I am online. There may be some discrepancy between what a disconnection looks like on my client versus the server. I am not super familiar with the internal terminology or logic of WS, but when I send a disconnect event in my client API, it comes back as "cancelled." This is expected behavior for the client, but perhaps the server is expecting a different type of disconnection / using different terminology. 

Nevertheless, I think Ethan has not been on squidchat for the last 20 minutes.

**Comment by heisler98** [comment]
Aha, I found some logs for you.
[sequoia-06152023.log](https://github.com/tiberloop/squidchat-issues/files/11753373/sequoia-06152023.log)

It appears the server is understanding the socket cancellation as a disconnect. I never receive an online status event. The `/ws/online` endpoint also does not update once a socket closes.

**Comment by colingoodman** [comment]
I am leaving users as keys in my hash table upon disconnect, just letting the value pairs hang as empty lists. I just fixed this, so /ws/online will be a little more accurate. Will verify that offline is emitted automatically upon socket disconnect.

**Comment by heisler98** [comment]
There are rudimentary online indicators.
